---
# tasks file for iptables-raw

- name: iptables-raw | install iptables services
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: iptables-nft-services
    state: present
  when: not install_legacy_service

- name: iptables-raw | install epel repo
  become: true
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: install_legacy_service

- name: iptables-raw | install install_legacy iptables
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: iptables-legacy
    state: present
  when: install_legacy_service

- name: iptables-raw | get list of services
  become: true
  service_facts:

- name: iptables-raw | disable firewalld
  become: true
  service:
    name: firewalld
    state: stopped
    enabled: false
  when: >-
    (iptables_raw_disable_firewalld | default(True)) and (
      ('firewalld' in ansible_facts.services) or
      ('firewalld.service' in ansible_facts.services)
    )

- name: iptables-raw | enable iptables
  become: true
  service:
    name: iptables
    state: started
    enabled: true
